version: 2
jobs:
  build:
    working_directory: /branch-druid
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run:
          name: Package
          command: |
            mvn package

workflows:
  version: 2
  build:
    jobs:
      - build
